---
name: SSL Expiry Check
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
jobs:
  ssl_expiry_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run SSL Expiry Check
        run: python ssl_expiry_check.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Configure SSH
        run: cd  ~/.ssh echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa 
         chmod 600 ~/.ssh/id_rsa ssh-keyscan -H 65.1.132.122 >> ~/.ssh/known_hosts
      - name: Run command on server
        run: |
          ssh root@65.1.132.122 "ls"
